version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_LOGIN: postgres
      POSTGRES_PASSWORD: 1998
    ports:
      - 5432:5432
    networks:
      - 3dModel
    command: ["postgres", "-c", "log_statement=all"]

  spring:
    image: web2:latest
    depends_on:
      - db
    ports:
      - 8189:8189
      - 8000:8000
    networks:
      - 3dModel

networks:
  3dModel:
    driver: bridge